COURSE_ACTS(COURSE_BOB, _(" 1 BATALLON BOB-OMB"),
       _("GRAN BOB-OMB EN LA CIMA")     , _("CARRERA CON KOOPA EL VELOZ") , _("DISPARA HACIA LA ISLA EN EL CIELO"),
       _("BUSCA LAS 8 MONEDAS ROJAS")          , _("MARIO ALADO HACIA EL CIELO")        , _("DETRAS DE LA JAULA DE CHAIN CHOMP"))

COURSE_ACTS(COURSE_WF, _(" 2 FORTALEZA WHOMP"),
       _("APLASTA AL GRAN WHOMP")        , _("HACIA LA CIMA DE LA FORTALEZA")    , _("VUELA HACIA LA GRAN PLATAFORMA"),
       _("MONEDAS ROJAS EN LA ISLA FLOTANTE"), _("CAE EN LA ISLA ENJAULADA")    , _("CHOCA CONTRA LA MURALLA"))

COURSE_ACTS(COURSE_JRB, _(" 3 BAHIA JOLLY ROGER"),
       _("SAQUEO EN EL BARCO HUNDIDO")    , _("PUEDE LA ANGUILA SALIR A JUGAR?") , _("TESORO EN LA CUEVA OCEANICA"),
       _("MONEDAS ROJAS EN EL BARCO A FLOTE")  , _("CHOCA EN EL PILAR DE PIEDRA")     , _("A TRAVES DE LA CORRIENTE"))

COURSE_ACTS(COURSE_CCM, _(" 4 COLINA NEVADA"),
       _("DESLIZANDOSE A LA META")             , _("PEQUENO PINGUINO PERDIDO")             , _("CARRERA CONTRA EL GRAN PINGUINO"),
       _("DESLIZANDOME POR 8 MONEDAS ROJAS")  , _("EL MUNECO DE NIEVE PERDIO LA CABEZA")       , _("ESCUELA DE SALTO PARED"))

COURSE_ACTS(COURSE_BBH, _(" 5 MANSION EMBOOJADA"),
       _("TEMPORADA DE BOOS")            , _("CABALGA EL CARRUSEL BOO") , _("SECRETOS DE LOS LIBROS EMBOOJADOS"),
       _("BUSCA LAS 8 MONEDAS ROJAS")          , _("BALCON DEL GRAN BOO")             , _("OJO EN LA SALA SECRETA"))

COURSE_ACTS(COURSE_HMC, _(" 6 LA CUEVA LABERINTICA"),
       _("LA BESTIA ACUATICA EN LA CUEVA")  , _("ELEVATE POR 8 MONEDAS ROJAS")       , _("MARIO CABEZA-METALICA MUEVETE!"),
       _("NAVEGANDO EN LA NIEBLA TOXICA")     , _("UNA SWOOPER ESCAPADA!")     , _("CUIDADO! ROCAS GIRATORIAS"))

COURSE_ACTS(COURSE_LLL, _(" 7 TIERRA VOLCANICA"),
       _("COCINANDO CON GRAN BULLY")            , _("TRES TRISTES BULLIES")             , _("8 MONEDAS ROJAS EN UN ROMPECABEZAS"),
       _("TRONCO GIRATORIO ARDIENTE")           , _("PIES CALIENTES EN EL VOLCAN")  , _("TOUR EN ELEVADOR ADENTRO DEL VOLCAN"))

COURSE_ACTS(COURSE_SSL, _(" 8 DUNAS MOVEDIZAS"),
       _("EN LOS TALONES DEL GRAN PAJARO") , _("BRILLO EN LA PUNTA PIRAMIDAL")      , _("DENTRO DE UNA ANTIGUA PIRAMIDE"),
       _("DE PIE EN LOS CUATRO PILARES"), _("VOLANDO POR 8 MONEDAS ROJAS")   , _("ROMPECABEZAS PIRAMIDAL"))

COURSE_ACTS(COURSE_DDD, _(" 9 MUELLE ATROZ"),
       _("A BORDO DEL SUBMARINO BOWSER")            , _("COFRES CONTRA CORRIENTE")         , _("MONEDAS ROJAS EN LOS POSTES"),
       _("DENTRO DE LA CORRIENTE")        , _("EL PREMIO DE LA MANTA RAYA")        , _("COLECCION DE GORRAS..."))

COURSE_ACTS(COURSE_SL, _("10 VENTISCA CONGELANTE"),
       _("MUNECO DE NIEVE CABEZON")            , _("CONGELA AL BULLY")          , _("EN EL FRIO PROFUNDO"),
       _("ESCAPE DEL ESTANQUE CONGELADO")  , _("ENCORAZADO POR MONEDAS ROJAS") , _("ADENTRO DEL IGLU"))

COURSE_ACTS(COURSE_WDW, _("11 SEQUIAS HUMEDAS"),
       _("IMPACTANTES FLECHAS ELECTRICAS!")         , _("LA CIMA DEL PUEBLO")               , _("SECRETOS PROFUNDOS DEL CIELO"),
       _("ELEVADOR EXPRESS--APURATE!")   , _("VE AL PUEBLO POR MONEDAS ROJAS")      , _("CARRERA RAPIDA DENTRO DEL PUEBLO!"))

COURSE_ACTS(COURSE_TTM, _("12 MONTANA ESCARPADA"),
       _("ESCALADA EN MONTANA")            , _("MISTERIOS DEL MONO ENJAULADO")    , _("HONGOS MIEDOSOS, MONEDAS ROJAS"),
       _("RESBALADERA MONTANOSA MISTERIOSA")       , _("DETRAS DE LA CASCADA") , _("DISPARADO AL HONGO SOLITARIO"))

COURSE_ACTS(COURSE_THI, _("13 LA GRAN PEQUENA ISLA"),
       _("ARRANCA LA PLANTA PIRANA")      , _("LA CIMA DE LA GRAN ISLA"), _("REVANCHA CONTRA KOOPA EL VELOZ"),
       _("5 PEQUENITOS SECRETITOS")       , _("MONEDAS ROJAS DEL WIGGLER")           , _("HAZ QUE WIGGLER SE RETUERZA"))

COURSE_ACTS(COURSE_TTC, _("14 RELOJ TIC-TAC"),
       _("RUEDA HASTA LA JAULA")            , _("LOS PENDULOS Y LA FOSA")     , _("NECESITAS UNA MANECILLA?"),
       _("ENCIMA DE UN TWHOMP")           , _("SINCRONIZADO CON LAS PLATAFORMAS")    , _("MONEDAS ROJAS MAS ALLA DEL TIEMPO"))

COURSE_ACTS(COURSE_RR, _("15 CRUCERO ARCOIRIS"),
       _("PASEO ARCOIRIS")  , _("LA MANSION EN EL CIELO")      , _("MONEDAS REVOLVIDAS EN EL LABERINTO"),
       _("BALANCEO EN LA BRISA")        , _("TRIANGULOS TRUCADOS!")             , _("EN ALGUN LUGAR SOBRE EL ARCOIRIS"))

SECRET_STAR(COURSE_BITDW, _("   BOWSER EN EL MUNDO OSCURO"))
SECRET_STAR(COURSE_BITFS, _("   BOWSER EN EL OCEANO DE FUEGO"))
SECRET_STAR(COURSE_BITS, _("   BOWSER EN EL CIELO"))
SECRET_STAR(COURSE_PSS, _("   LA RESBALADERA SECRETA DE LA PRINCESA"))
SECRET_STAR(COURSE_COTMC, _("   CAVERNA DE LA GORRA METALICA"))
SECRET_STAR(COURSE_TOTWC, _("   TORRE DE LA GORRA ALADA"))
SECRET_STAR(COURSE_VCUTM, _("   FOSA DE LA GORRA INVISIBLE"))
SECRET_STAR(COURSE_WMOTR, _("   MARIO ALADO SOBRE EL ARCOIRIS"))
SECRET_STAR(COURSE_SA, _("   EL ACUARIO SECRETO"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   ESTRELLAS SECRETAS"))

EXTRA_TEXT(0, _("UNA DE LAS ESTRELLAS SECRETAS DEL CASTILLO!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
